name: Build Docker Image

on:
  push:
    tags:
      - 1.*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Dockerfile
        run: docker build -t ghcr.io/kraussmaffei/awscli-kubectl:${{ github.ref_name }} .

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/kraussmaffei/awscli-kubectl:${{ github.ref_name }}